name = "satyasri-homecare"
compatibility_date = "2025-09-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "satyasri-enquiries"
database_id = "58bbe5e9-0ae4-4872-8572-a96b29710121"
